/**
 * mock data for the employee table
 * @type {[{firstName: string, lastName: string, zipCode: string, city: string, street: string, dateOfBirth: string, state: string, department: string, startDate: string},{firstName: string, lastName: string, zipCode: string, city: string, street: string, dateOfBirth: string, state: string, department: string, startDate: string},{firstName: string, lastName: string, zipCode: string, city: string, street: string, dateOfBirth: string, state: string, department: string, startDate: string},{firstName: string, lastName: string, zipCode: string, city: string, street: string, dateOfBirth: string, state: string, department: string, startDate: string},{firstName: string, lastName: string, zipCode: string, city: string, street: string, dateOfBirth: string, state: string, department: string, startDate: string},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]}
 */
export const employeeData = [
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-02',
        department: 'Engineering',
        dateOfBirth: '1990-01-01',
        street: '3 Hollywood Blvd',
        city: 'Los Angeles',
        state: 'CL',
        zipCode: '62701',
    },
    {
        firstName: 'Antoine',
        lastName: 'Martin',
        startDate: '2022-01-01',
        department: 'Legal',
        dateOfBirth: '1990-03-01',
        street: '3 Homer St',
        city: 'Springfield',
        state: 'IL',
        zipCode: '12345',
    },
    {
        firstName: 'Zoe',
        lastName: 'Amaro',
        startDate: '2022-02-01',
        department: 'Sales',
        dateOfBirth: '1992-01-01',
        street: '123 Main St',
        city: 'Moab',
        state: 'UT',
        zipCode: '9876',
    },
];
